---
title: "Fertility final"
format: html
editor: visual
---

##Setting up libraries

```{r}
library(tidyverse)
library(mosaic)
library(skimr)
library(visdat)
library(naniar)
library(janitor)
library(ggformula)
library(dplyr)
library(tinytable)
library(DT)
library(crosstable)
```

##Reading Data

```{r}
Fertility <- readr::read_delim("Data/Fertility.csv") %>% 
  janitor::clean_names(case="snake")
Fertility
```


```{r}
Fertility_1 <- Fertility %>%
  mutate(
    morekids = as.factor(morekids),
    gender1 = as.factor(gender1),
    gender2 = as.factor(gender2),
    afam = as.factor(afam),
    hispanic = as.factor(hispanic),
    other = as.factor(other)
  ) %>%
 
  dplyr::relocate(age, afam, hispanic, other, gender1,gender2,morekids, .after= rownames)
Fertility_1
```
```{r}
Fertility_1 %>%
  filter(afam=="yes") %>% 
  dplyr::summarise(
    mean_work = mean(work, na.rm=T),
    sd_work = sd(work,na.rm=T),
    min_work = min(work, na.rm=T),
    max_work = max(work, na.rm=T)
  )
```
```{r}
Fertility_1 %>%
  filter(hispanic=="yes") %>% 
  dplyr::summarise(
    mean_work = mean(work, na.rm=T),
    sd_work = sd(work,na.rm=T),
    min_work = min(work, na.rm=T),
    max_work = max(work, na.rm=T)
  )
```
```{r}
Fertility_1 %>%
  filter(other=="yes") %>% 
  dplyr::summarise(
    mean_work = mean(work, na.rm=T),
    sd_work = sd(work,na.rm=T),
    min_work = min(work, na.rm=T),
    max_work = max(work, na.rm=T)
  )
```